language: node_js
node_js: 4.1
script:
    - npm test
    - npm run build
deploy:
    provider: script
    script: node deploy.js
    skip_cleanup: true
    on:
        branch: master
env:
  secure: UZ3HgGfnzOoVzXxl1REmtbyaC3jL+0xkgUsmGrVcvXRodUnKRwS5rIY8QyP5tiaeaX0jcyxoCyyzU1syTD1xvdVvR4/qJDu0fz+Y3ahHU03cbH7ujTIdnmvsfzkw/3Iac7O68jnnNWdI7gPm9sGsFN2zRK/rZ2y5X88Ey4enn5rnI7u2q9/aAiH+KlvjDy29Y3171f6WJWDe5CmDhk/DruzM0oCuQfQkENyHcdb7cZGC4bPUJyngeuE2hmbZwdejTU0Vpr0/X4tro7Et65S+yj2PWNf819fKluR6x5BrqaTOFwBGNK06Y5nnxAi89x65ZTV8XgZF1t/OF13UdvtclaHpQBqJwlm37u0NcO4KgHEk5TBZpuvSKFcB85/+S0jSxT3mOEZ//GPVOsmC3XcN4CXMv5yqurM3VgioPYbC8r2Fr8L2CCYd0gPWuVbCCxYbnv9GmefMvby3lkNJQg0dVcomjiZjDVfHraz6+hVNmviCHWqwW4XW6sofIgDxuZCu3qTPGYyu7bFmZcurnH/ss7+uw/CQrO8V5TSC0XsUjsHsa+Q34BFivDabDMq+pNUPuHEDHVqqFJ+c+MwA1IU1HGvGm2bcIJkBUsmMLsOV8S44L7x1Y0naFqUqZfqmZAn0qi0gsypsIuc3By848dbDP9B2JfCbVPykuEBYPldTVP0=
