language: node_js
node_js: 4.1
script:
    - npm test
    - npm run build
deploy:
    provider: script
    script: node deploy.js
    skip_cleanup: true
    on:
        branch: master
env:
  secure: pdII/tHEGQSqEXyD0cFNDxsofx1zyE0V42fC/YrFrMvQb7FqRK3RMKPS7ReYBHK9jnnCIA28ctedBEyAKnmyo6UvJH/qh1MwMjhkC6hO+QbM5cn8pbiU0JPFy94EHXjKqTRTgorK0ozVIChkdnWPKnEidcY67K1kKMXqfJ+f3nZlJ+eUFWcp9WpgRkTV+IvOsnTdepH6CPtwqwV/LSICkjU+oAgFi4bTdNprPWDKgkHCY/fOvbqjDivpC9HhCoIDQTKSctbI4QPgWpp+/ZGo2lhaCIegnxERhWb2HPTxKjekO1iadaTQCs/sIO2rHqEBNGiWFnjH8dv4S/E4HrFnikYzdF7ZlolbMpnGT/++7LX8cECCdRGosvA2NEGWFUyathv7VB7hdqFPRfZDVxgPobJo8aSNn7+Z4IefTSOD0czCYIH3lL4oDB422+/EGgBq1dTye3DpbpnCsyM41zsOugesNIsAqgpv8uBQkTummZ/LTcnnHWeRdb8fFSygxjSbdnJmcFxzZcq/f0ZzW3XzlvblMk6XkZ5zlLwowMUi+vFVMeMe1zAffHzCr5XHfW3Yq9TknxwWa8mmCVo2UfxNtlSqaeZtyuwvUzqxstu6P0kt5ZJuGOfyOsS32Yug83fDYy2MshcPGbkoT59f9A/yXjvMKCLPeDfOhQRZ4ugMr/Y=
