language: node_js
node_js: 4.1
script:
    - npm test
    - npm run build
deploy:
    provider: script
    script: bash .deploy.sh
    skip_cleanup: true
    on:
        branch: master
env:
  - secure: OUrQfgqIoCm3yTmy3pwM6VHTk4PWEM7ey4O/bnXqdWkvUTSsGEpeMlim6z8Efjym8fZPFcCAruyGKeoYcMbYfCM9RE8999GYgQeDloqoGir33zH4Yb24lCgJ0flVP3h7Lo6H4O5gKv/1t5ABbD72oQaLERPFfhcr5NZk8B7k/5YiFiKZ6W3R6+/7JtaaKLBTCkD3Mb/ZD69nFT4bSlTkxoeetEAaF26EdENI3BmoHr4qJL3OoTwnWlfdxhgH4g/T8TBGRuAs4x1lIUa6E5ArmlOjCqrF6MiFPqPXmz8jpzao6WhxeIB7bklZ1fE6kGiZy4hda7F1Zu/7seFuUNAK4+em5eTIK6weGXBoKFrLhPHvbNnRDxcJMAwDeR+iiv4Y6uCMnXMJ6Mwe5Xb+M3QAtYSwVIgJUo/K1zz38h4/OyIZfxO7MxzM9T+aAC0UNZQMT4KoZJv+LNHQRfSiZNZTTIFARt0fljpLGRPcUUen1u1eEl3h7vnrHi8mLsOTePv4eMNRY/ZQudG0Cf5c2JRAWQwDkqLg1wRBm0/LmSOIF38j8dGi5r6rU86QTZkIuO47IE1aVr90t5RaHChZw94NrJsfsh5++wgG5boUZ1bSY1amnIPdEGTKfbNIBa2S5e49pW/JFb9YiVR/px1v9k31UULf/NnGLX9A20N3+NeVL1A=
  - FORM_URL=https://formkeep.com/f/55d47b4e9575
